[package]
name = "da-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "da"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
ssh2 = { version = "0.9", features = ["vendored-openssl"] }
anyhow = "1"
cliclack = "0.3"
indicatif = "0.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "chrono"] }
walkdir = "2"
dirs = "5"
tar = "0.4"
flate2 = "1"

[profile.release]
opt-level = "z"     # otimiza para tamanho
lto = true          # link-time optimization
codegen-units = 1   # melhor otimização, build mais lento
strip = true        # remove símbolos de debug
panic = "abort"     # sem unwinding -> binário menor
